<a href="https://colab.research.google.com/github/Nazif-25/DSA/blob/main/Graphs_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Shortest path with bfs on undirected graph

In [8]:
from collections import deque

def bfs_shortest_distances(graph, start, n):
    # Initialize distances with "infinity"
    INF = float('inf')
    distance = [INF] * (n + 1)  # 1-based indexing

    # Set the start node's distance to 0
    distance[start] = 0
    queue = deque([start])

    while queue:
        current = queue.popleft()

        for neighbor in graph[current]:
            if distance[neighbor] == INF:
                distance[neighbor] = distance[current] + 1
                queue.append(neighbor)

    return distance
# Graph from earlier (8 nodes, 1-based indexing)
graph = {
    0: [1,3],
    1: [0,2,3],
    2: [1, 6],
    3: [0,4],
    4: [3,5],
    5: [4,6],
    6: [2,5, 7,8],
    7: [6, 8],
    8: [6, 7]
}

n = 8  # Total number of nodes
start_node = 0

distances = bfs_shortest_distances(graph, start_node, n)
print(distances)
# Print distances from node 1 to all others
for i in range(1, n + 1):
    if distances[i] == float('inf'):
        print(f"Node {i} is unreachable from node {start_node}")
    else:
        print(f"Shortest distance from node {start_node} to node {i} is {distances[i]}")


[0, 1, 2, 1, 2, 3, 3, 4, 4]
Shortest distance from node 0 to node 1 is 1
Shortest distance from node 0 to node 2 is 2
Shortest distance from node 0 to node 3 is 1
Shortest distance from node 0 to node 4 is 2
Shortest distance from node 0 to node 5 is 3
Shortest distance from node 0 to node 6 is 3
Shortest distance from node 0 to node 7 is 4
Shortest distance from node 0 to node 8 is 4


In [7]:
from collections import deque

def bfs_longest_distances(graph, start, n):
    # Initialize distances with -infinity
    NEG_INF = float('-inf')
    distance = [NEG_INF] * (n + 1)
    distance[start] = 0

    queue = deque([start])

    while queue:
        current = queue.popleft()
        for neighbor in graph[current]:
            if distance[neighbor] == NEG_INF:
                distance[neighbor] = distance[current] + 1
                queue.append(neighbor)

    return distance
graph = {
    0: [1,3],
    1: [0,2,3],
    2: [1, 6],
    3: [0,4],
    4: [3,5],
    5: [4,6],
    6: [2,5, 7,8],
    7: [6, 8],
    8: [6, 7]
}
# print(bfs_longest_distances(graph, 0, 8)) INCORRECT

[0, 1, 2, 1, 2, 3, 3, 4, 4]


In [9]:
from collections import deque

def bfs_farthest_node(graph, start, n):
    visited = [False] * (n + 1)
    distance = [0] * (n + 1)
    queue = deque([start])
    visited[start] = True

    farthest_node = start

    while queue:
        current = queue.popleft()

        for neighbor in graph[current]:
            if not visited[neighbor]:
                visited[neighbor] = True
                distance[neighbor] = distance[current] + 1
                queue.append(neighbor)
                if distance[neighbor] > distance[farthest_node]:
                    farthest_node = neighbor

    return farthest_node, distance[farthest_node], distance
graph = {
    0: [1,3],
    1: [0,2,3],
    2: [1, 6],
    3: [0,4],
    4: [3,5],
    5: [4,6],
    6: [2,5, 7,8],
    7: [6, 8],
    8: [6, 7]
}
farthest_node, longest_path , distance= bfs_farthest_node(graph, 0, 8)
print(farthest_node, longest_path)
print(distance)


7 4
[0, 1, 2, 1, 2, 3, 3, 4, 4]


#Bipartite graph

In [ ]:
from collections import deque

def is_bipartite(graph, n):
    # -1 means unvisited, 0 and 1 are the two colors
    color = [-1] * (n + 1)

    for start in range(1, n + 1):
        if color[start] == -1:
            queue = deque()
            queue.append(start)
            color[start] = 0

            while queue:
                node = queue.popleft()
                for neighbor in graph[node]:
                    if color[neighbor] == -1:
                        color[neighbor] = 1 - color[node]
                        queue.append(neighbor)
                    elif color[neighbor] == color[node]:
                        return False  # Same color neighbor → not bipartite
    return True

# -------------------------
# Graph input (from the map)
graph = {
    1: [2],
    2: [1, 5, 6],
    3: [5],
    4: [5],
    5: [2, 3, 4, 8],
    6: [2, 7],
    7: [ 6, 8],
    8: [5, 7]
}

n = 8  # Number of nodes/divisions

# Check if the graph is bipartite
if is_bipartite(graph, n):
    print("The graph is bipartite. A valid division into Group A and B is possible.")
else:
    print("The graph is NOT bipartite. Such a division is NOT possible.")


The graph is NOT bipartite. Such a division is NOT possible.


#adjacency matrix

In [ ]:
# adjacency matrix
def create_matrix():
    # here graph is a matrix
    graph = np.zeros((4,4), dtype = int)
    # matrix[row][col] = edge_weight
    graph[0][1] = 5
    graph[0][2] = 10
    graph[0][3] = 7
    graph[1][0] = 2
    graph[1][2] = 14
    graph[1][3] = 13
    graph[2][0] = 8
    graph[2][1] = 4
    graph[2][3] = 9
    graph[3][0] = 3
    graph[3][1] = 6
    graph[3][2] = 1

    return graph

graph = create_matrix()
print(graph)

[[ 0  5 10  7]
 [ 2  0 14 13]
 [ 8  4  0  9]
 [ 3  6  1  0]]


In [ ]:
def twoDlistTraversal(graph):
    rows = len(graph)
    cols = len(graph[0])
    result = []
    for r in range(rows):
        for c in range(cols):
            if graph[r][c] != 0:
                result.append(f"{graph[r][c]} -> ")
    print("".join(result))
twoDlistTraversal(graph)

5 -> 10 -> 7 -> 2 -> 14 -> 13 -> 8 -> 4 -> 9 -> 3 -> 6 -> 1 -> 


In [ ]:
def find_net_spend(graph):
    rows = len(graph)
    cols = len(graph[0])
    arr = np.array([0]*4)
    arr2 = np.array([0]*4)

    index_of_arr = 0
    for r in range(rows):
        rows_sum = 0
        for c in range(cols):
            rows_sum += graph[r][c]
        arr[index_of_arr] = rows_sum
        index_of_arr += 1

    index_of_arr2 = 0
    for c in range(cols):
        cols_sum = 0
        for r in range(rows):
            cols_sum += graph[r][c]
        arr2[index_of_arr2] = cols_sum
        index_of_arr2 += 1

    arr3 = np.array([0]*4)
    for i in range(len(arr)):
        net_spend = arr[i] - arr2[i]
        arr3[i] = net_spend
    return arr3

print(find_net_spend(graph))

[  9  14  -4 -19]


In [ ]:
cols_sum = graph.sum(axis=0)
rows_sum = graph.sum(axis=1)
net_spend = rows_sum - cols_sum
print(net_spend)


[  9  14  -4 -19]


# Better approach

In [ ]:
def reverse_edge(graph):
    size = len(graph.matrix)
    original_matrix = graph.matrix.copy()
    # here we are flattening the 2D matrix into 1D list
    # in the 2D matrix there are 6 by 6 elements therefore 36 elements hence size*size
    for i in range(size * size):
        # floor dividing i by size gives row number
        # modulus division of i by size gives column number
        r = i // size
        c = i % size
        if r%2==1:
            if original_matrix[r][c] == 1:
                graph.matrix[c][r] = 1
                graph.matrix[r][c] = 0

    return graph
graph = reverse_edge(graph)
graph.print_graph()

In [ ]:
class Node:
    def __init__(self, data):
        self.data = data

class Graph:
    def __init__(self, size):
        self.nodes_list = []
        self.matrix = np.zeros((size,size), dtype = int)

    def add_node(self, elem):
        node = Node(elem)
        self.nodes_list += [node]

    def add_edge(self, src, dst):
        self.matrix[src][dst] = 1

    def check_edge(self, src, dst):
        if self.matrix[src][dst] == 1:
            return True
        return False

    def print_graph(self):
        rows = len(self.matrix)
        cols = len(self.matrix[0])
        print(" ", end=" ")

        for node in self.nodes_list:
            print(node.data, end=" ")
        print()

        for r in range(rows):
            print(self.nodes_list[r].data, end=" ")
            for c in range(cols):
                print(self.matrix[r][c], end=" ")
            print()


In [ ]:
graph = Graph(5)
graph.add_node("A")
graph.add_node("B")
graph.add_node("C")
graph.add_node("D")
graph.add_node("E")
graph.add_edge(0, 1)
graph.add_edge(1, 2)
graph.add_edge(2, 3)
graph.add_edge(4, 0)

graph.print_graph()

print(graph.check_edge(0,1))
print(len(graph.nodes_list))

  A B C D E 
A 0 1 0 0 0 
B 0 0 1 0 0 
C 0 0 0 1 0 
D 0 0 0 0 0 
E 1 0 0 0 0 
True
5


In [ ]:
# here graph is an object of Graph (class)
def BFS(graph, start):
    total_vertex = len(graph.nodes_list)
    visited = np.array([False]*total_vertex)
    queue = Queue()
    visited[start] = True
    queue.enqueue(start)
    while queue.is_empty() == False:
        u = queue.dequeue()
        print(u)
        for v in range(total_vertex):
            if graph.matrix[u][v] != 0 and visited[v] == False:
                visited[v] = True
                queue.enqueue(v)
BFS(graph,2)

2
3


In [ ]:
# here graph is an object of Graph (class)
def DFS(graph, start):
    total_vertex = len(graph.nodes_list)
    visited = np.array([False]*total_vertex)
    stack = Stack()
    visited[start] = True
    stack.push(start)
    while stack.is_empty() == False:
        u = stack.pop()
        print(u)
        for v in range(total_vertex):
            if graph.matrix[u][v] != 0 and visited[v] == False:
                visited[v] = True
                stack.push(v)
DFS(graph, 0)


0
1
2
3


#Stack

In [ ]:
class Node:
    def __init__(self, elem):
        self.elem = elem
        self.next = None
class Stack:
    def __init__(self):
        self.top = None

    def push(self, elem):
        new_node = Node(elem)
        new_node.next = self.top
        self.top = new_node

    def pop(self):
        if self.is_empty():
            raise IndexError("Stack is empty")
        popped_elem = self.top.elem
        self.top = self.top.next
        return popped_elem

    def peek(self):
        if self.is_empty():
            raise IndexError("Stack is empty")
        return self.top.elem

    def is_empty(self):
        return self.top is None

# Cycle detection in directed graph using DFS

In [ ]:
class Node:
    def __init__(self, elem):
        self.elem = elem
        self.next = None
class Stack:
    def __init__(self):
        self.top = None

    def push(self, elem):
        new_node = Node(elem)
        new_node.next = self.top
        self.top = new_node

    def pop(self):
        if self.is_empty():
            raise IndexError("Stack is empty")
        popped_elem = self.top.elem
        self.top = self.top.next
        return popped_elem

    def peek(self):
        if self.is_empty():
            raise IndexError("Stack is empty")
        return self.top.elem

    def is_empty(self):
        return self.top is None
# class Node:
#     def __init__(self, data):
#         self.data = data

class Graph:
    def __init__(self, size):
        self.nodes_list = []
        self.matrix = np.zeros((size,size), dtype = int)

    def add_node(self, elem):
        node = Node(elem)
        self.nodes_list += [node]

    def add_edge(self, src, dst):
        self.matrix[src][dst] = 1

    def check_edge(self, src, dst):
        if self.matrix[src][dst] == 1:
            return True
        return False

    def print_graph(self):
        rows = len(self.matrix)
        cols = len(self.matrix[0])
        print(" ", end=" ")

        for node in self.nodes_list:
            print(node.elem, end=" ")
        print()

        for r in range(rows):
            print(self.nodes_list[r].elem, end=" ")
            for c in range(cols):
                print(self.matrix[r][c], end=" ")
            print()

def detect_cycle(graph, start):
    total_vertex = len(graph.nodes_list)
    visited = np.array([False]*total_vertex)
    flag = np.array([-1]*total_vertex)
    stack = Stack()
    visited[start] = True
    stack.push(start)
    flag[start] = 0
    while stack.is_empty() == False:
        u = stack.pop()
        print(u)
        for v in range(total_vertex):
            if graph.matrix[u][v]!=0 and visited[v] == False:
                    visited[v] = True
                    stack.push(v)
                    flag[v] = 0
        if 0 in flag:
            print(flag)
            return True
    return False
graph = Graph(5)
graph.add_node("A")
graph.add_node("B")
graph.add_node("C")
graph.add_node("D")
graph.add_node("E")
graph.add_edge(0, 1)
graph.add_edge(0, 2)
graph.add_edge(1, 2)
graph.add_edge(1, 3)
graph.add_edge(3, 4)
# graph.add_edge(4, 1)

graph.print_graph()

detect_cycle(graph, 0)

  A B C D E 
A 0 1 1 0 0 
B 0 0 1 1 0 
C 0 0 0 0 0 
D 0 0 0 0 1 
E 0 0 0 0 0 
0
[ 0  0  0 -1 -1]


True

# Queue

In [ ]:
import numpy as np

In [ ]:
class Node:
    def __init__(self, elem):
        self.elem = elem
        self.next = None

class Graph:
    def __init__(self, size):
        self.nodes_list = []
        self.matrix = np.zeros((size,size), dtype = int)

    def add_node(self, elem):
        node = Node(elem)
        self.nodes_list += [node]

    def add_edge(self, src, dst):
        self.matrix[src][dst] = 1

    def check_edge(self, src, dst):
        if self.matrix[src][dst] == 1:
            return True
        return False

    def print_graph(self):
        rows = len(self.matrix)
        cols = len(self.matrix[0])
        print(" ", end=" ")

        for node in self.nodes_list:
            print(node.elem, end=" ")
        print()

        for r in range(rows):
            print(self.nodes_list[r].elem, end=" ")
            for c in range(cols):
                print(self.matrix[r][c], end=" ")
            print()

class Queue:
    def __init__(self):
        self.front = self.rear = None

    def enqueue(self, elem):
        new_node = Node(elem)
        if self.rear is None:
            self.front = self.rear = new_node
            return
        self.rear.next = new_node
        self.rear = new_node

    def dequeue(self):
        if self.is_empty():
            raise IndexError("Queue is empty")
        removed_elem = self.front.elem
        self.front = self.front.next
        if self.front is None:
            self.rear = None
        return removed_elem

    def peek(self):
        if self.is_empty():
            raise IndexError("Queue is empty")
        return self.front.elem

    def is_empty(self):
        return self.front is None

def detect_cycle(graph, start):
    total_vertex = len(graph.nodes_list)
    visited = np.array([False]*total_vertex)
    flag = np.array([-1]*total_vertex)
    queue = Queue()
    visited[start] = True
    if flag[start] == -1:
        flag[start] = 0
        queue.enqueue(start)
    while queue.is_empty() == False:
        u = queue.dequeue()
        print(u)
        for v in range(total_vertex):
            if graph.matrix[u][v]!=0 and visited[v] == False:
                    visited[v] = True
                    if flag[v] == 0:
                        return True
                    if flag[v] == -1:
                        flag[v] = 0
                        queue.enqueue(v)
                    if flag[v] == 1:
                        continue

    return False
graph = Graph(5)
graph.add_node("A")
graph.add_node("B")
graph.add_node("C")
graph.add_node("D")
graph.add_node("E")
graph.add_edge(0, 1)
graph.add_edge(1, 0)
graph.add_edge(1, 2)
graph.add_edge(2, 1)
graph.add_edge(2, 3)
graph.add_edge(2, 4)
graph.add_edge(3, 2)
graph.add_edge(3, 4)
graph.add_edge(4, 2)
graph.add_edge(4, 3)


graph.print_graph()

detect_cycle(graph, 0)

  A B C D E 
A 0 1 0 0 0 
B 1 0 1 0 0 
C 0 1 0 1 1 
D 0 0 1 0 1 
E 0 0 1 1 0 
0
1
2
3
4


False

In [ ]:
import numpy as np
from collections import deque

class Node:
    def __init__(self, elem):
        self.elem = elem
        self.next = None

class Graph:
    def __init__(self, size):
        self.nodes_list = []
        self.matrix = np.zeros((size, size), dtype=int)

    def add_node(self, elem):
        node = Node(elem)
        self.nodes_list.append(node)

    def add_edge(self, src, dst):
        # For undirected graph, add both directions
        self.matrix[src][dst] = 1
        self.matrix[dst][src] = 1

    def check_edge(self, src, dst):
        return self.matrix[src][dst] == 1

    def print_graph(self):
        print(" ", end=" ")
        for node in self.nodes_list:
            print(node.elem, end=" ")
        print()

        for r in range(len(self.matrix)):
            print(self.nodes_list[r].elem, end=" ")
            for c in range(len(self.matrix[0])):
                print(self.matrix[r][c], end=" ")
            print()

def detect_cycle(graph, start):
    total_vertex = len(graph.nodes_list)
    visited = [False] * total_vertex
    parent = [-1] * total_vertex
    queue =Queue()

    visited[start] = True
    queue.enqueue(start)

    while queue:
        u = queue.dequeue()
        for v in range(total_vertex):
            if graph.matrix[u][v] == 1:
                if not visited[v]:
                    visited[v] = True
                    parent[v] = u
                    queue.enqueue(v)
                elif parent[u] != v:
                    # If the neighbor is visited and not the parent, cycle exists
                    return True
    return False

# Test Case
graph = Graph(5)
graph.add_node("A")
graph.add_node("B")
graph.add_node("C")
graph.add_node("D")
graph.add_node("E")
graph.add_edge(0, 1)  # A - B
graph.add_edge(1, 0)  # B - A
graph.add_edge(1, 2)  # B - C
graph.add_edge(2, 1)  # C - B
graph.add_edge(2, 3)  # C - D
graph.add_edge(2, 4)  # C - E
graph.add_edge(3, 2)  # D - C
graph.add_edge(3, 4)  # D - E
# graph.add_edge(4, 2)  # E - C
# graph.add_edge(4, 3)  # E - D

graph.print_graph()
print("Cycle detected:", detect_cycle(graph, 0))  # Expected: True (since there's a cycle, e.g., B-C-D-E-B)

  A B C D E 
A 0 1 0 0 0 
B 1 0 1 0 0 
C 0 1 0 1 1 
D 0 0 1 0 1 
E 0 0 1 1 0 
Cycle detected: True


# Breadth First Search (BFS)

In [ ]:
# adjacency matrix
import numpy as np
def create_matrix():
    # here graph is a matrix
    graph = np.zeros((6,6), dtype = int)
    # matrix[row][col] = edge_weight
    graph[0][5] = 15
    graph[1][2] = 44
    graph[1][5] = 8
    graph[2][4] = 10
    graph[2][1] = 44
    graph[2][3] = 9
    graph[3][2] = 9
    graph[3][4] = 7
    graph[3][5] = 15
    graph[4][2] = 10
    graph[4][3] = 7
    graph[5][0] = 15
    graph[5][1] = 8
    graph[4][3] = 7
    graph[5][3] = 15
    return graph
graph = create_matrix()
print(graph)

[[ 0  0  0  0  0 15]
 [ 0  0 44  0  0  8]
 [ 0 44  0  9 10  0]
 [ 0  0  9  0  7 15]
 [ 0  0 10  7  0  0]
 [15  8  0 15  0  0]]


In [ ]:
# here graph is a matrix
def BFS(graph, start):
    total_vertex = len(graph)
    visited = np.array([False]*total_vertex)
    queue = Queue()
    visited[start] = True
    queue.enqueue(start)
    while queue.is_empty() == False:
        u = queue.dequeue()
        print(u)
        for v in range(total_vertex):
            if graph[u][v] != 0 and visited[v] == False:
                visited[v] = True
                queue.enqueue(v)
BFS(graph,2)

2
1
3
4
5
0


#Depth First Search (DFS)

#adjacency list

Difference between print_graph() and printGraph() respectively:

| Aspect         | print_graph()      | printGraph()                                               |
| -------------- | ------------- | -------------------------------------------------------- |
| 📄 Readability | Good          | Slightly better (clearer separation of logic + output)   |
| 🔄 Flexibility | Less flexible | More flexible for future features                        |
| 🖨 Print calls | Many          | Fewer                                                    |
| 🚀 Performance | Fine          | Potentially slightly faster with large graphs (less I/O) |


In [ ]:
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None
class Graph:
    def __init__(self, vertices):
        self.V = vertices
        self.array = [None]*vertices

    def add_edge(self, src, dst):
        node = Node(dst)
        node.next = self.array[src]
        self.array[src] = node

        node = Node(src)
        node.next = self.array[dst]
        self.array[dst] = node

    def print_graph(self):
        for src in range(self.V):
            temp = self.array[src]
            print(f"Adjacency list of {src}",end=" ")
            while temp:
                print(f"--> {temp.data}",end=" ")
                temp = temp.next
            print()

    def printGraph(self):
        for src in range(self.V):
            connections = []
            temp = self.array[src]
            while temp:
                connections.append(f"-->{temp.data}")
                temp = temp.next
            print(f"Adjacency list of {src}:{''.join(connections)}")

    def convert_undirected_to_directed(self):
        for dst in range(self.V):
            temp = self.array[dst]
            while temp:
                src = temp.data
                self.remove_edge(src, dst)
                temp = temp.next

    def remove_edge(self, src, dst):
        prev = None
        temp = self.array[src]
        while temp:
            if temp.data == dst:
                if prev:
                    prev.next = temp.next
                else:
                    self.array[src] = temp.next
                return
            prev = temp
            temp = temp.next

    def convert_directed_to_undirected(self):
        for dst in range(self.V):
            temp = self.array[dst]
            while temp!=None:
                src = temp.data
                if not self.edge_exists(src, dst):
                    node = Node(dst)
                    node.next = self.array[src]
                    self.array[src] = node
                temp = temp.next

    def edge_exists(self, src, dst):
        temp = self.array[src]
        while temp:
            if temp.data == dst:
                return True
            temp = temp.next
        return False

In [ ]:
graph = Graph(5)
graph.add_edge(0, 1)
graph.add_edge(0, 4)

graph.add_edge(1, 2)
graph.add_edge(1, 3)
graph.add_edge(1, 4)

graph.add_edge(2, 3)
graph.add_edge(3, 4)

graph.print_graph()

graph.printGraph()

Adjacency list of 0 --> 4 --> 1 
Adjacency list of 1 --> 4 --> 3 --> 2 --> 0 
Adjacency list of 2 --> 3 --> 1 
Adjacency list of 3 --> 4 --> 2 --> 1 
Adjacency list of 4 --> 3 --> 1 --> 0 
Adjacency list of 0:-->4-->1
Adjacency list of 1:-->4-->3-->2-->0
Adjacency list of 2:-->3-->1
Adjacency list of 3:-->4-->2-->1
Adjacency list of 4:-->3-->1-->0


In [ ]:
graph.convert_undirected_to_directed()
graph.print_graph()

Adjacency list of 0 --> 4 --> 1 
Adjacency list of 1 --> 4 --> 3 --> 2 
Adjacency list of 2 --> 3 
Adjacency list of 3 --> 4 
Adjacency list of 4 


In [ ]:
graph.convert_directed_to_undirected()
graph.print_graph()

Adjacency list of 0 --> 4 --> 1 
Adjacency list of 1 --> 0 --> 4 --> 3 --> 2 
Adjacency list of 2 --> 1 --> 3 
Adjacency list of 3 --> 2 --> 1 --> 4 
Adjacency list of 4 --> 3 --> 1 --> 0 
